### PR TITLE
Rainbow Effect

### PR DESCRIPTION
**Pull request by MKM12345**
Instead of a plain purple background on hover, I added a rainbow animation on hover for the ```<div class="dropdown">```. Please try this out and merge at your convenience. Look [here](https://replit.com/@KrakenVajraA/IntrepidSalmonCalculators#index.html) for an example.

### CODE REVIEW

**Comment by MKM12345** [comment]
You can change it if you just want one thing to have a rainbow animation.

**Comment by hamdivazim** [comment]
Nice, but the theme of the website is meant to be purple, hence the purple colour.

**Comment by MKM12345** [comment]
Just add one rainbow? It makes it eye catching

**Comment by hamdivazim** [comment]
As you are now a collaborator you can add these changes in yourself in moderation. Thanks for contributing to CodeGlob!

**Comment by MKM12345** [comment]
@hamdivazim Thanks! But could you please try and do this? I'm a little busy, it's fine if you don't.

**Pull request merged**
